spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_test
    username: rajiku
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      schema


  sql:
    init:
      mode: always
      encoding: utf-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      spring:
        sql:
          init:
            encoding: